
[random]

	[random.random]
		shut_up_redshotz = false

	[random.gfs_commands]
		autometic_gfs_commands = true
		gfs_ender_pearl_command = true

	[random.anti-monkey]
		anti-monkey = true

	[random.party_commands]
		party_commands = true

	[random.rng_drops]
		rng_drop_paste = false

	[random.pearl]
		pearl = true

[general]

	[general.general]
		name = true

	[general.test]
		title_color = "255,255,0,0"

	[general.e]
		e = "ddsdsdsds"

	[general.ender_pearl_refills]
		autorefill = true

[chat]

	[chat.chat]
		hide_useless_messages_main = false
		hide_useless_messages = true

	[chat.party_commands]
		leap_announcement = true
		party_commands = true

	[chat.uayor]
		anti_escrow = true

[dungeons]

	[dungeons.f7]
		leap_to_healer_debug_message = true
		leap_to_healer_message = true
		wishing_messages = true
		selection_of_terminal = 0
		message_for_wishing = "wish"
		leap_for_p2 = false
		f7_terminal_calling = true

	[dungeons.dungeons]
		dungeon_start_timer = false
		leap_announcement = true
		hide_leap_messages = 0

	[dungeons.messages]
		leap_to_healer_debug_message = true
		leap_to_healer_message = true

	[dungeons.titles]
		dungeon_title_toggle = true
		"dungeon_key/door_title" = true
		"bonzo_mask/phoenix_cooldown" = true
		bonzo_mask_cooldown = true
		"blood_ready/done_title" = true

	[dungeons.uayor]
		manuelrefill = false
		manualrefill = false
		autorefill = true
		auto_open_potion_bag = false

	[dungeons.leaping]
		leap_to_healer_message = true
		leap_announcement = true
		show_title_instad_of_message = true
		"only_send_leapmessage_in_boss_(f7)" = false
		hide_leap_messages = 0

[messages]

	[messages.debug]
		hides_debug_messages = true
		hide_debug_messages = false

	[messages."hide_useless_messages:_auction_house"]
		"show_all_useless_auction_house_messages!" = false
		"auction_house:_processing_purchase_message" = false
		"auction_house:_claiming_bin_message" = false
		"auction_house:_escrow_coin_message" = false
		"party_commands:_show_all_party_command_messages" = false

	[messages."hide_messages:_party_commands"]
		"party_commands:_party_allinvite_message" = true
		"show_all_party_command_messages!" = true
		"party_commands:_party_help_message" = true
		"party_commands:_party_warp_message" = true
		"party_commands:_show_all_party_command_messages" = false
		"party_commands:_party_pearls_message" = true

	[messages.hideuselessmessages]
		name22 = false
		name = false

	[messages."hide_useless_messages:_bazzar"]
		"bazaar:_no_buyer_message" = false
		"bazaar:_sell_offer_message_message" = false
		"bazaar:_sell_offer_message" = false
		"bazaar:_too_much_message" = false
		"bazaar:_goods_in_escrow_message" = false
		show_all_useless_bazaar_messages = false
		"bazaar:_claim_offer_message_message" = false
		"show_all_useless_bazaar_messages!" = false
		"bazaar:_claim_offer_message" = false
		"bazaar:_buy_offer_message" = false
		"bazaar:_cancel_offer_message" = false
		"bazaar:_insta_sell_message" = false
		"bazaar:_insta_buy_message" = false
		"bazaar:_buy_offer_message_message" = false
		"bazaar:_cancel_offer_message_message" = false

	[messages.hide_useless_messages]
		"bazaar:_no_buyer_message" = false
		hide_useless_messages_main = true
		"bazaar:_sell_offer_message_message" = false
		name22 = false
		"bazaar:_too_much_message" = false
		"bazaar:_goods_in_escrow_message" = false
		"bazaar:_insta_sell_message" = false
		"bazaar:_insta_buy_message" = false
		show_all_useless_bazaar_messages = false
		"bazaar:_claim_offer_message_message" = false
		"bazaar:_buy_offer_message_message" = false
		"bazaar:_cancel_offer_message_message" = false

[undefined]
	hides_debug_messages = false
	party_commands = true

